-- ============================================================
-- EXTENSION
-- ============================================================

CREATE EXTENSION IF NOT EXISTS postgis;


-- ============================================================
-- COMMON CODE
-- ============================================================

CREATE TABLE tb_cmn_code (
    cid         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    p_cid       BIGINT,

    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(100) NOT NULL,

    c_lvl       INTEGER      NOT NULL DEFAULT 1,

    dsc         VARCHAR(500),
    status      CHAR(1)      NOT NULL DEFAULT 'Y',

    c_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    u_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT uq_tb_cmn_code_pcid_code
        UNIQUE (p_cid, code),

    CONSTRAINT fk_tb_cmn_code_parent
        FOREIGN KEY (p_cid)
        REFERENCES tb_cmn_code (cid)
);


-- ============================================================
-- REGION
-- 행정구역 계층 + 영역(Polygon)
-- ============================================================

CREATE TABLE tb_reg (
    rid         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    p_reg_id    BIGINT,

    code        VARCHAR(20)  NOT NULL UNIQUE,
    name        VARCHAR(100) NOT NULL,
    level       INTEGER      NOT NULL,

    geom        GEOMETRY,

    status      CHAR(1)      NOT NULL DEFAULT 'Y',

    c_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    u_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT fk_tb_reg_parent
        FOREIGN KEY (p_reg_id)
        REFERENCES tb_reg (rid)
);


-- ============================================================
-- USER
-- ============================================================

CREATE TABLE tb_users (
    uid         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    email       VARCHAR(100) NOT NULL UNIQUE,
    pwd         VARCHAR(255) NOT NULL,
    nickname    VARCHAR(100) NOT NULL,

    type        VARCHAR(20)  NOT NULL,
    status      VARCHAR(20)  NOT NULL,

    rid         BIGINT,

    c_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    u_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT fk_tb_users_region
        FOREIGN KEY (rid)
        REFERENCES tb_reg (rid)
);


-- ============================================================
-- FILE
-- ============================================================

CREATE TABLE tb_file (
    file_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    file_stre_cours     VARCHAR(2000) NOT NULL,
    stre_file_nm        VARCHAR(255)  NOT NULL,
    orignl_file_nm      VARCHAR(255),

    file_extsn          VARCHAR(20) NOT NULL,
    file_cn             TEXT,
    file_size           BIGINT,

    c_date              TIMESTAMP WITHOUT TIME ZONE NOT NULL
);


-- ============================================================
-- STORE
-- 음식점 정보 + 실제 위치(Point)
-- ============================================================

CREATE TABLE tb_store (
    store_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name        VARCHAR(200) NOT NULL,

    ctg         VARCHAR(20)  NOT NULL,
    rid         BIGINT       NOT NULL,

    address     VARCHAR(500) NOT NULL,

    lat         DECIMAL(10, 7) NOT NULL,
    lon         DECIMAL(10, 7) NOT NULL,

    geom        GEOMETRY,

    phone       VARCHAR(30),

    status      VARCHAR(20) NOT NULL,

    dsc         TEXT,

    c_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    u_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT fk_tb_store_region
        FOREIGN KEY (rid)
        REFERENCES tb_reg (rid)
);


-- ============================================================
-- STORE - TAG MAPPING
-- ============================================================

CREATE TABLE mtb_store_tag (
    store_id    BIGINT      NOT NULL,
    tag_code    VARCHAR(50) NOT NULL,

    c_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT pk_mtb_store_tag
        PRIMARY KEY (store_id, tag_code),

    CONSTRAINT fk_mtb_store_tag_store
        FOREIGN KEY (store_id)
        REFERENCES tb_store (store_id)
);


-- ============================================================
-- EVENT
-- 이벤트 정보 + 실제 위치(Point)
-- ============================================================

CREATE TABLE tb_event (
    eid         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    title       VARCHAR(300) NOT NULL,

    ctg         VARCHAR(20) NOT NULL,
    status      VARCHAR(20) NOT NULL,

    rid         BIGINT NOT NULL,

    s_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    e_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    dsc         TEXT NOT NULL,

    address     VARCHAR(500),

    lat         DECIMAL(10, 7),
    lon         DECIMAL(10, 7),

    geom        GEOMETRY,

    file_id     BIGINT,

    created_by  BIGINT NOT NULL,

    c_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    u_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT fk_tb_event_region
        FOREIGN KEY (rid)
        REFERENCES tb_reg (rid),

    CONSTRAINT fk_tb_event_user
        FOREIGN KEY (created_by)
        REFERENCES tb_users (uid),

    CONSTRAINT fk_tb_event_file
        FOREIGN KEY (file_id)
        REFERENCES tb_file (file_id)
);


-- ============================================================
-- EVENT - TAG MAPPING
-- ============================================================

CREATE TABLE mtb_event_tag (
    eid         BIGINT      NOT NULL,
    tag_code    VARCHAR(50) NOT NULL,

    c_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT pk_mtb_event_tag
        PRIMARY KEY (eid, tag_code),

    CONSTRAINT fk_mtb_event_tag_event
        FOREIGN KEY (eid)
        REFERENCES tb_event (eid)
);


-- ============================================================
-- EVENT COMMENT
-- 댓글 / 대댓글
-- ============================================================

CREATE TABLE tb_event_cmt (
    cmt_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    eid         BIGINT NOT NULL,
    uid         BIGINT NOT NULL,

    cmt         TEXT NOT NULL,

    p_cmt_id    BIGINT,

    status      VARCHAR(20) NOT NULL,

    c_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    u_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT fk_tb_event_cmt_event
        FOREIGN KEY (eid)
        REFERENCES tb_event (eid),

    CONSTRAINT fk_tb_event_cmt_user
        FOREIGN KEY (uid)
        REFERENCES tb_users (uid),

    CONSTRAINT fk_tb_event_cmt_parent
        FOREIGN KEY (p_cmt_id)
        REFERENCES tb_event_cmt (cmt_id)
);


-- ============================================================
-- INDEXES
-- FK / 검색용 기본 인덱스
-- ============================================================

CREATE INDEX ix_tb_cmn_code_p_cid
    ON tb_cmn_code (p_cid);

CREATE INDEX ix_tb_reg_p_reg_id
    ON tb_reg (p_reg_id);

CREATE INDEX ix_tb_users_rid
    ON tb_users (rid);

CREATE INDEX ix_tb_store_rid
    ON tb_store (rid);

CREATE INDEX ix_tb_store_ctg
    ON tb_store (ctg);

CREATE INDEX ix_tb_event_rid
    ON tb_event (rid);

CREATE INDEX ix_tb_event_created_by
    ON tb_event (created_by);

CREATE INDEX ix_tb_event_file_id
    ON tb_event (file_id);

CREATE INDEX ix_tb_event_date
    ON tb_event (s_date, e_date);

CREATE INDEX ix_tb_event_cmt_eid
    ON tb_event_cmt (eid);

CREATE INDEX ix_tb_event_cmt_uid
    ON tb_event_cmt (uid);

CREATE INDEX ix_tb_event_cmt_p_cmt_id
    ON tb_event_cmt (p_cmt_id);

-- ============================================================
-- SPATIAL INDEXES
-- PostGIS
-- ============================================================

CREATE INDEX ix_tb_reg_geom
    ON tb_reg
    USING GIST (geom);

CREATE INDEX ix_tb_store_geom
    ON tb_store
    USING GIST (geom);

CREATE INDEX ix_tb_event_geom
    ON tb_event
    USING GIST (geom);